const initAuth: AuthBody = {
  azureId: "",
  fullname: "",
  countryCode: "",
  phone: "",
  email: "",
  isEmailVerified: false,
  isIdentityVerified: false,
  isAddressVerified: false,
  isCompanyVerified: "PENDING",
  isUserVerified: "PENDING",
  status: 0,
  roles: "",
  reasonForRejection: "",
  token: "",
  tfaEnabled: false,
  priceList: 0,
  limitList: NaN,
  roleId: NaN,
};

const initCompany: CompanyDetailsType = {
  company: {
    id: NaN,
    userId: "",
    companyName: "",
    companyLegalForm: "",
    countryCode: "",
    companyEmail: "",
    isEmailVerified: false,
    adminRemarks: "",
    beneficialOwnerPosition: "",
    clientId: "",
    companyUrl: "",
    owner: "",
    phone: "",
    profileImageUrl: "",
    reasonForRejection: "",
    verificationStatus: "PENDING",
    accountStatus: "",
    verificationLevel: "",
    createdAt: "",
    updatedAt: "",
    priceList: 0,
    limitList: NaN,
    User: {
      id: NaN,
      azureId: "",
      firstname: "",
      lastname: "",
      countryCode: "",
      phone: "",
      email: "",
      dob: "",
      status: 0,
      active: false,
      isEmailVerified: false,
      isIdentityVerified: false,
      isAddressVerified: false,
      isCompanyVerified: "PENDING",
      isUserVerified: "PENDING",
      roles: "",
      reasonForRejection: "",
      profileImgLink: "",
      tfaEnabled: false,
      clientId: "",
      personType: "",
      gender: "Male",
      nationality: "",
      createdBy: "",
      language: "",
      defaultCurrency: "",
      customPriceList: "",
      priceList: 0,
      limitList: NaN,
      createdAt: "",
      verificationStatus: "",
      verificationLevel: "",
      updatedAt: "",
      companyProfileId: NaN,
    },
    CompanyEntityInfo: {
      id: "",
      companyProfileId: "",
      country: "",
      natureOfBusiness: "",
      registrationNumber: "",
      incorporationDate: "",
      city: "",
      addressLine1: "",
      addressLine2: "",
      postalCode: "",
      sameOperatingAddress: false,
      operatingAddressCity: "",
      operatingAddressAddressLine1: "",
      operatingAddressAddressLine2: "",
      operatingAddressPostalCode: "",
      createdAt: "",
      updatedAt: "",
      BusinessNature: {
        id: "",
        name: "",
      },
      Country: {
        name: "",
      },
    },
    UserCompanyAssociations: [],
    CompanyPaymentsInfo: {},
  },
  relatedDocuments: [],
  legalAgreements: [],
};

const initPriceList: PriceList = {
  id: NaN,
  name: "",
  clientType: "",
  companyType: "",
  standard: false,
  externalFeeEnabled: false,
  FxMarkupFees: [],
  TransferFees: [],
  RecurringFees: [],
  createdAt: "",
};

const initLimitList: Limits = {
  transferDirection: "",
  id: NaN,
  clientVerificationLevel: "",
  clientType: "",
  personType: "",
  name: "",
  description: "",
  status: "",
  Thresholds: [],
  ExchangeLimits: [],
};

const initPerson: UserStore = {
  id: NaN,
  azureId: "",
  firstname: "",
  lastname: "",
  countryCode: "",
  phone: "",
  email: "",
  dob: "",
  active: false,
  isEmailVerified: false,
  isIdentityVerified: false,
  isAddressVerified: false,
  isCompanyVerified: "PENDING",
  isUserVerified: "PENDING",
  status: 0,
  verificationStatus: "",
  verificationLevel: "",
  roles: "",
  reasonForRejection: "",
  profileImgLink: "",
  tfaEnabled: false,
  clientId: "",
  personType: "",
  gender: "",
  nationality: "",
  createdBy: "",
  language: "",
  defaultCurrency: "",
  customPriceList: "",
  createdAt: "",
  updatedAt: "",
  priceList: 0,
  limitList: NaN,
  companyProfileId: NaN,
  UserVerification: {
    id: "",
    city: "",
    state: "",
    country: "",
    addressLine1: "",
    addressLine2: "",
    postalCode: "",
    Country: { id: NaN, currency: "", countryCode: NaN, name: "" },
  },
  UserCompanyAssociations: [],
  LegalAgreements: [],
  LegalDocuments: [],
  ContactDetails: [],
  documents: [],
  checkLimits: [],
  UserAssets: [],
  EuroTemplates: [],
  Thresholds: undefined,
};

const initAdmin: AdminProfile = {
  profileImgLink: "",
  companyLegalName: "",
  companyAddress: "",
  email: "",
  tabName: "",
  createdAt: "",
  updatedAt: "",
  deletedAt: "",
  id: 0,
  updatedWithApi: false,
};

// const initTransaction: TransactionDetails = {
//   id: "",
//   userId: "",
//   transactionId: "",
//   assetId: "",
//   operationType: "",
//   sourceId: "",
//   destinationId: "",
//   sourceAddress: "",
//   destinationAddress: "",
//   sourceType: "",
//   destinationType: "",
//   status: "",
//   subStatus: "",
//   txHash: "",
//   numOfConfirmations: "",
//   note: "",
//   operation: "",
//   destinationAssetId: "",
//   orderType: "",

//   UserAsset: {
//     id: "",
//     userId: "",
//     assetId: "",
//     walletId: "",
//     assetAddress: "",
//     User: initPerson,
//   },

//   Assets: {
//     id: "",
//     fireblockAssetId: "",
//     name: "",
//     icon: "",
//     krakenAssetId: "",
//   },
//   Asset: {
//     id: "",
//     fireblockAssetId: "",
//     name: "",
//     icon: "",
//     krakenAssetId: "",
//   },
//   OperationType: {
//     name: "",
//     displayName: "",
//   },
//   TransactionFees: {
//     id: "",
//     transactionId: "",
//     amount: "",
//     netAmount: "",
//     networkFee: "",
//     amountUSD: "",
//     feeCurrency: "",
//     feeValue: "",
//     rate: "",
//   },
// };

const initAdministrator: AdministratorUsersType = {
  id: 0,
  firstname: "",
  lastname: "",
  accessRoles: {
    displayName: "",
    id: "",
    name: "",
  },
  active: false,
  email: "",
};

const initGlobalStore: globalStoreType = {
  auth: initAuth,
  company: initCompany,
  pricelist: initPriceList,
  persons: initPerson,
  administrator: initAdministrator,
  admin: initAdmin,
  limitList: initLimitList,
  // transaction: initTransaction,
};

export default initGlobalStore;

export { initAuth };
