import React, { useEffect, useState } from "react";
import Companies from "./banking/companies";
import Head from "next/head";
import { useGlobalStore } from "~/store";

const Home = () => {
  const admin = useGlobalStore((state) => state.admin);

  const [state] = useGlobalStore((state) => [state.admin]);

  useEffect(() => {
    if (!state?.updatedWithApi) {
      useGlobalStore.getState().syncAdminProfile();
    }
  }, [state]);

  return (
    <>
      <Head>
        <title>{admin?.tabName ?? "CRM Admin"}</title>

        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Companies />
    </>
  );
};

export default Home;
