import Head from "next/head";
import { useContext, type ReactNode, Suspense } from "react";
import Sidebar from "~/common/Sidebar";
import Topbar from "~/common/Topbar";
import { SidebarContext } from "~/context/SidebarProvider";
import { useRouter } from "next/router";
import { useGlobalStore } from "~/store";

type Props = {
  children: ReactNode;
};

const routesArray = [
  "/auth/login",
  "/auth/signup",
  "/auth/setup-2fa",
  "/auth/verify-2fa",
  "/auth/forgotPassword",
  "/auth/resetPassword",
];

const Layout = ({ children }: Props) => {
  const router = useRouter();
  const pathName = router.pathname;

  const sidebarprop = useContext(SidebarContext);

  const admin = useGlobalStore((state) => state.admin);

  function Loading() {
    return "Loading...";
  }

  return (
    <>
      <Head>
        {admin && <title>{admin?.tabName}</title>}
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-[100vh]">
        <div className="">{!routesArray.includes(pathName) && <Sidebar />}</div>
        <div className="w-full overflow-y-auto">
          <div className="sticky top-0 z-20 ">
            {!routesArray.includes(pathName) && <Topbar />}
          </div>
          <div className={`${!routesArray.includes(pathName) ? "px-8" : ""}`}>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </div>
        </div>
      </div>
    </>
  );
};

export default Layout;
